name = "moeru-ai-airi"
compatibility_date = "2025-04-01"
preview_urls = true
main = "src/worker.ts"

[assets]
directory = "./dist"
not_found_handling = "none"
binding = "ASSETS"

[vars]
API_ORIGIN = "https://api.airi.build"
